// Generates bootstrap/embedded-app.js from app/ (run by build.ps1).
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.argv[2] || process.cwd();
const out = process.argv[3] || join(root, 'bootstrap', 'embedded-app.js');
const files = ['bot.js', 'media.js', 'package.json'].map((n) => ({
  name: n,
  content: readFileSync(join(root, 'app', n), 'utf8'),
}));
const body =
  '// Generated by build.ps1 from app/ - do not edit by hand.\n' +
  'export const EMBEDDED_APP = ' + JSON.stringify(files) + ';\n';
writeFileSync(out, body, 'utf8');
console.log('embedded app written to ' + out);